Repository oz-main-project-team-02/vita-gamemate-fe, pull requests merged in 2024-11, with the labels that each got.

#41 cd 조건 변경, 배포환경 로그인 안되던 버그 수정, 코드 스플리팅 제거
  .github/workflows/deploy.yml
  src/App.tsx
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/LoginModal.tsx
  src/components/Common/MateCard.tsx
  src/components/Common/OrderModal.tsx
  src/components/Common/VitaPrice.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/UserDetailPage/GameOrderSection.tsx
  src/config/store.ts
  src/layouts/CommonLayout.tsx
  src/pages/EventPage.tsx
  src/pages/KakaoCallback.tsx
  src/pages/user/GameMatePage.tsx
  src/pages/user/UserDetailPage.tsx
  src/utils/delay.ts
  tsconfig.app.tsbuildinfo
Labels: enhancement

#42 에러바운더리 추가, 상세페이지 skeleton ui 일부 추가, toss css 제거 및 ui 리디자인
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/UserDetailPage/ReviewList.tsx
  src/components/UserDetailPage/ReviewSection.tsx
  src/config/store.ts
  src/config/types.ts
  src/hooks/useChatRoomWebSocket.ts
  src/layouts/CommonLayout.tsx
  src/main.tsx
  src/pages/payments/PaymentCheckout.tsx
  src/pages/payments/SuccessPage.tsx
  src/pages/user/GameMatePage.tsx
  src/pages/user/UserDetailPage.tsx
  src/toss.css
  src/utils/ErrorBoundary.tsx
  src/utils/ErrorCatcher.tsx
  src/utils/QueryClientBoundary.tsx
  src/utils/showToastError.ts
Labels: enhancement

#45 채팅: 읽지 않은 메세지 알림 기능 추가, 토큰 인증 추가, 게임의뢰 정보부분 페이지네이션 기능 추가
  src/components/Common/ChatMateRequestInfo.tsx
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/ChatModal.tsx
  src/components/Common/ChatRenderMessages.tsx
  src/components/Common/ChatSubmitForm.tsx
  src/components/Common/Pagination.tsx
  src/components/UserDetailPage/UserBar.tsx
  src/config/store.ts
  src/config/types.ts
  src/hooks/useChatListWebSocket.ts
  src/hooks/useChatRoomWebSocket.ts
Labels: bug, enhancement

#48 새로운 채팅방 생성시 채팅목록 데이터 캐싱되던 버그 수정
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/ChatModal.tsx
  src/components/Common/ChatRenderMessages.tsx
  src/components/UserDetailPage/UserBar.tsx
  src/config/store.ts
Labels: bug

#56 📦 chore: uninstall react-hook-form
  .gitignore
  package-lock.json
  package.json
Labels: enhancement
