Repository oz-main-project-team-02/vita-gamemate-fe, pull requests merged in 2024-10, with the labels that each got.

#10 게임 메이트 등록페이지 UI디자인
  .github/pull_request_template.md
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vitaLogo.png
  src/App.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/imgs/lol.png
  src/components/Common/Footer.tsx
  src/components/Common/Header.tsx
  src/components/Common/TitleIntro.tsx
  src/components/EditInfoPage/FilterList.tsx
  src/components/EditInfoPage/ProfileImg.tsx
  src/components/GameMatePage/GameSelect.tsx
  src/components/GameMatePage/TeamBattleForm.tsx
  src/components/Homepage/CategorySlider.tsx
  src/components/Homepage/EventSlider.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/global.css
  src/layouts/CommonLayout.tsx
  src/main.tsx
  src/pages/CategoryPage.tsx
  src/pages/CoinPage.tsx
  src/pages/EditInfoPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/GameMatePage.tsx
  src/pages/HomePage.tsx
  src/pages/OrdersPage.tsx
  src/pages/UserDetailPage.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: documentation, enhancement

#18 채팅모달 생성(채팅 목록, 채팅창 조회, 메세지 전송)
  src/api/chat.ts
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/ChatModal.tsx
  src/components/Common/ChatRenderMessages.tsx
  src/components/Common/ChatSubmitForm.tsx
  src/components/Common/Header.tsx
  src/components/Common/ProfileImage.tsx
  src/config/store.ts
  src/config/types.ts
  src/layouts/CommonLayout.tsx
  src/mocks/dummy.ts
  src/mocks/handlers.ts
  src/utils/dateUtils.ts
  src/utils/imageUtils.ts
  src/utils/onClickOutside.ts
  tailwind.config.js
Labels: enhancement

#19 인터셉터 조건추가, 전역 로그인 상태 확인 기능 추가, 로그인 시 지갑 상태 업데이트 추가
  src/App.tsx
  src/api/client.ts
  src/assets/imgs/button_plus.svg
  src/components/CoinPage/CoinBox.tsx
  src/components/Common/GameDropdown.tsx
  src/components/Common/Header.tsx
  src/components/Common/LoginStatusChecker.tsx
  src/components/Common/VitaPrice.tsx
  src/components/GameMatePage/GameSection.tsx
  src/components/Homepage/CategorySlider.tsx
  src/config/const.ts
  src/config/store.ts
  src/config/types.ts
  src/pages/CoinPage.tsx
  src/pages/KakaoCallback.tsx
  src/pages/UserDetailPage.tsx
  src/routes/VitaPrivateRoute.tsx
  vite.config.ts
Labels: bug, enhancement

#20 API 명세서 기반 기능 추가
  src/api/getGameMatesByCategory.ts
  src/components/CategoryPage/CheckBoxButtonGroup.tsx
  src/components/CategoryPage/FilterSidebar.tsx
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/CategoryPage/RadioButtonGroup.tsx
  src/components/Common/GameDropdown.tsx
  src/components/Common/LoginStatusChecker.tsx
  src/components/Common/MateCard.tsx
  src/components/Homepage/GameCategorySection.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/config/const.ts
  src/config/types.ts
  src/mocks/dummy.ts
  src/pages/CategoryPage.tsx
  src/pages/KakaoCallback.tsx
  src/pages/UserDetailPage.tsx
Labels: bug, enhancement

#21 채팅방 생성 기능 추가
  src/api/chat.ts
  src/components/Common/Header.tsx
  src/layouts/CommonLayout.tsx
  src/mocks/dummy.ts
  src/mocks/handlers.ts
  src/pages/UserDetailPage.tsx
Labels: bug, enhancement

#22 review API 추가, API 모듈화 및 API 문서 주석 추가
  src/api/auth.ts
  src/api/getGameMatesByCategory.ts
  src/api/index.ts
  src/api/mate.ts
  src/api/review.ts
  src/api/user.ts
  src/api/wallet.ts
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/CoinPage/CoinBox.tsx
  src/components/Common/LoginStatusChecker.tsx
  src/components/Common/MateCard.tsx
  src/components/Common/ProfileDropdown.tsx
  src/components/Common/VitaPrice.tsx
  src/components/EditInfoPage/FilterList.tsx
  src/components/GameMatePage/GameMateApplicationForm.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/UserDetailPage/ReviewList.tsx
  src/config/store.ts
  src/config/types.ts
  src/pages/KakaoCallback.tsx
  src/pages/UserDetailPage.tsx
Labels: enhancement

#23 🐛 fix: 로그인 안되는 버그 수정
  src/pages/KakaoCallback.tsx
Labels: enhancement

#24 mocking -> server API 변경, skeleton UI 추가, 결제모달 UI구현, 의뢰 API추가
  src/App.tsx
  src/api/auth.ts
  src/api/client.ts
  src/api/getGameMatesByCategory.ts
  src/api/index.ts
  src/api/mate.ts
  src/api/request.ts
  src/api/user.ts
  src/api/wallet.ts
  src/components/CategoryPage/CheckBoxButtonGroup.tsx
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/CoinPage/CoinBox.tsx
  src/components/Common/Header.tsx
  src/components/Common/LoginStatusChecker.tsx
  src/components/Common/OrderModal.tsx
  src/components/Common/ProfileDropdown.tsx
  src/components/EditInfoPage/FilterList.tsx
  src/components/GameMatePage/GameMateApplicationForm.tsx
  src/components/Homepage/CategorySlider.tsx
  src/components/Homepage/EventSlider.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/OrderPage/OrderBox.tsx
  src/components/OrderPage/Request.tsx
  src/components/OrderPage/Response.tsx
  src/components/OrderPage/Review.tsx
  src/components/skeleton/SkeletonMateCard.tsx
  src/components/skeleton/SkeletonReviewCard.tsx
  src/components/skeleton/SkeletonTodayGameMate.tsx
  src/config/store.ts
  src/config/types.ts
  src/global.css
  src/layouts/CommonLayout.tsx
  src/pages/CategoryPage.tsx
  src/pages/KakaoCallback.tsx
  src/pages/OrdersPage.tsx
  src/pages/UserDetailPage.tsx
  src/utils/delay.ts
Labels: enhancement

#25 채팅창에 의뢰버튼 ui 추가 및 웹소켓 로직 추가
  src/api/chat.ts
  src/api/socket.ts
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/ChatModal.tsx
  src/components/Common/ChatSubmitForm.tsx
  src/components/Common/OrderModal.tsx
  src/config/store.ts
  src/config/types.ts
  src/hooks/useOnClickOutside.ts
  src/layouts/CommonLayout.tsx
  src/mocks/dummy.ts
Labels: enhancement

#27 토스 테스트 결제 기능 추가(서버 API연결), 리뷰 API 추가, Pages폴더 구조화
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/api/review.ts
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/CoinPage/CoinBox.tsx
  src/components/Common/FilterList.tsx
  src/components/Common/GameCard.tsx
  src/components/Common/GameDropdown.tsx
  src/components/Common/Header.tsx
  src/components/Common/LoginModal.tsx
  src/components/Common/LoginStatusChecker.tsx
  src/components/Common/MateCard.tsx
  src/components/Common/OrderModal.tsx
  src/components/Common/ProfileDropdown.tsx
  src/components/GameMatePage/DescriptionSection.tsx
  src/components/Homepage/CategorySlider.tsx
  src/components/Homepage/EventSlider.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/OrderPage/OrderBox.tsx
  src/components/OrderPage/Request.tsx
  src/components/OrderPage/Response.tsx
  src/components/OrderPage/Review.tsx
  src/config/types.ts
  src/layouts/CommonLayout.tsx
  src/mocks/handlers.ts
  src/mocks/http.ts
  src/pages/CategoryPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/GoogleCallback.tsx
  src/pages/HomePage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/FailPage.tsx
  src/pages/payments/PaymentBilling.tsx
  src/pages/payments/PaymentCheckout.tsx
  src/pages/payments/SuccessPage.tsx
  src/pages/user/CoinPage.tsx
  src/pages/user/EditInfoPage.tsx
  src/pages/user/GameMatePage.tsx
  src/pages/user/OrdersPage.tsx
  src/pages/user/PaymentsPage.tsx
  src/pages/user/UserDetailPage.tsx
  src/server/payments.controller.js
  src/server/payments.router.js
  src/server/payments.service.js
  src/server/server.js
  src/toss.css
  src/utils/delay.ts
Labels: enhancement

#28 불필요 패키지 삭제, 서버 삭제, 반응형 디자인 추가, 메시지 관련 버그 수정
  package-lock.json
  package.json
  src/api/review.ts
  src/components/CategoryPage/CheckBoxButtonGroup.tsx
  src/components/CategoryPage/FilterSidebar.tsx
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/CoinPage/CoinBox.tsx
  src/components/Common/FilterList.tsx
  src/components/Common/GameCard.tsx
  src/components/Common/GameDropdown.tsx
  src/components/Common/Header.tsx
  src/components/Common/ProfileImg.tsx
  src/components/Common/TitleIntro.tsx
  src/components/EditInfoPage/Birthday.tsx
  src/components/Homepage/CategorySection.tsx
  src/components/Homepage/CategorySlider.tsx
  src/components/Homepage/EventSection.tsx
  src/components/Homepage/EventSlider.tsx
  src/components/Homepage/GameCategorySection.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSection.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/config/types.ts
  src/global.css
  src/pages/CategoryPage.tsx
  src/pages/user/CoinPage.tsx
  src/pages/user/EditInfoPage.tsx
  src/pages/user/PaymentsPage.tsx
  src/pages/user/UserDetailPage.tsx
  src/server/payments.controller.js
  src/server/payments.router.js
  src/server/payments.service.js
  src/server/server.js
  src/toss.css
Labels: enhancement

#30 반응형 디자인 추가, 코인 결제 클릭 별 가격 토스페이먼츠 수정
  src/components/Common/FilterList.tsx
  src/components/Common/Gender.tsx
  src/components/Common/ProfileImg.tsx
  src/components/GameMatePage/GameSection.tsx
  src/components/GameMatePage/ImageSection.tsx
  src/components/GameMatePage/LevelSection.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/OrderPage/Request.tsx
  src/components/OrderPage/Response.tsx
  src/config/types.ts
  src/layouts/CommonLayout.tsx
  src/layouts/MypageLayout.tsx
  src/pages/CategoryPage.tsx
  src/pages/payments/PaymentCheckout.tsx
  src/pages/user/CoinPage.tsx
  src/pages/user/EditInfoPage.tsx
  src/pages/user/GameMatePage.tsx
  src/pages/user/OrdersPage.tsx
  src/pages/user/PaymentsPage.tsx
Labels: enhancement

#32 채팅 전송 및 메세지 불러오기, 채팅목록 업데이트
  src/api/chat.ts
  src/api/socket.ts
  src/api/websocket.ts
  src/components/Common/ChatMateRequestInfo.tsx
  src/components/Common/ChatMessageModal.tsx
  src/components/Common/ChatModal.tsx
  src/components/Common/ChatRenderMessages.tsx
  src/components/Common/ChatSubmitForm.tsx
  src/config/store.ts
  src/config/types.ts
  src/hooks/useChatListWebSocket.ts
  src/hooks/useChatRoomWebSocket.ts
  src/hooks/useWebSocketListener.ts
  src/mocks/dummy.ts
  src/pages/user/UserDetailPage.tsx
Labels: bug, enhancement

#33 의뢰 신청, 받은 의뢰 캐시 업데이트, 상태별 UI 추가, 기존 ui 변경, 리뷰 부분 버그 수정, 코인관련 버그수정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/mate.ts
  src/api/request.ts
  src/api/review.ts
  src/api/wallet.ts
  src/components/CategoryPage/GameCategoryCardList.tsx
  src/components/Common/Gender.tsx
  src/components/Common/OrderModal.tsx
  src/components/Common/Spinner.tsx
  src/components/GameMatePage/GameMateApplicationForm.tsx
  src/components/Homepage/CategorySlider.tsx
  src/components/Homepage/GameCategorySlider.tsx
  src/components/Homepage/GameMateSlider.tsx
  src/components/Homepage/RealTimeReviewsSection.tsx
  src/components/OrderPage/RenderSectionByStatus.tsx
  src/components/OrderPage/Request.tsx
  src/components/OrderPage/Response.tsx
  src/components/OrderPage/Review.tsx
  src/config/types.ts
  src/mocks/browser.ts
  src/mocks/dummy.ts
  src/mocks/handlers.ts
  src/mocks/http.ts
  src/pages/CategoryPage.tsx
  src/pages/user/CoinPage.tsx
  src/pages/user/EditInfoPage.tsx
  src/pages/user/GameMatePage.tsx
  src/pages/user/OrdersPage.tsx
  src/pages/user/PaymentsPage.tsx
  src/pages/user/UserDetailPage.tsx
Labels: enhancement
